CLASS zcl_zsegw_mpc_ext DEFINITION PUBLIC INHERITING FROM zcl_zsegw_mpc CREATE PUBLIC.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_zsegw_mpc_ext IMPLEMENTATION.
ENDCLASS.
